//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Try1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Course
    {
        public Course()
        {
            this.Enrolls = new HashSet<Enroll>();
        }
    
        public int CourseId { get; set; }

        [Required]
        public string CourseName { get; set; }

        
        [Required]
        public Nullable<int> CourseCredit { get; set; }

        [Display(Name="Course Price")]
        [Required]
        public Nullable<double> CoursePrice { get; set; }
    
        public virtual ICollection<Enroll> Enrolls { get; set; }
    }
}
