//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Try1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Enroll
    {
        public Enroll()
        {
            this.Installments = new HashSet<Installment>();
        }
    
        public int EnrollId { get; set; }
        [Required]
        public Nullable<int> StudentID { get; set; }
        [Required]
        public Nullable<int> CourseID { get; set; }
        [Required]
        public Nullable<int> ObtainedCredit { get; set; }
        [Required]
        public Nullable<double> AplicablePrice { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Installment> Installments { get; set; }
        public virtual Student Student { get; set; }
    }
}
