//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Try1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Installment
    {
        public int InstallmentId { get; set; }
        [Required]
        public Nullable<int> EnrollmentId { get; set; }
        [Required]
        public Nullable<double> Paid { get; set; }
    
        public virtual Enroll Enroll { get; set; }
    }
}
