//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Try1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public Student()
        {
            this.Enrolls = new HashSet<Enroll>();
        }
    
        public int StudentId { get; set; }
        [Required]
        [Display (Name="Student Name") ]
        public string StudentName { get; set; }

        
        [Display(Name="Student Address")]
        public string StudentAddress { get; set; }

        [Display(Name="Gender")]
        [Required]
        public string StudentGender { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required]
        public string Email { get; set; }
    
        public virtual ICollection<Enroll> Enrolls { get; set; }
    }
}
